---
title: Saimonhowlader.Github.Io
timezone: EST
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Saimon Howlader
markdown: kramdown
permalink: "/blog/:title"
sass:
  sass_dir: "./_scss"
  style: compressed
